#!/usr/bin/env node
/**
 * GBP Post Queue CLI
 *
 * Standalone entry point for GBP post generation.
 * Primarily used via the /gbp slash command, but can also run directly:
 *
 *   npm run gbp                              # Generate 14 posts, alternate days
 *   npm run gbp -- --count 21                # Custom count
 *   npm run gbp -- --frequency daily         # Post every day
 *   npm run gbp -- --start 2026-04-01        # Custom start date
 *   npm run gbp -- --preview-only            # Write gbp-queue.json without DB/images
 */

import { loadGBPQueue } from "./generate-gbp.js";
import { generateAndUploadAll } from "./gbp-image-gen.js";
import { ensureGBPTable, insertGBPPosts, getQueueSummary } from "./gbp-db.js";

const args = process.argv.slice(2);
const getArg = (f: string) => { const i = args.indexOf(f); return i !== -1 ? args[i + 1] : undefined; };
const hasFlag = (f: string) => args.includes(f);

const PREVIEW_ONLY = hasFlag("--preview-only");

function hr(c = "─", w = 64) { return c.repeat(w); }

async function main() {
  console.log();
  console.log(hr("═"));
  console.log("  📍  Antek Automation — GBP Post Queue");
  console.log(hr("═"));
  console.log();

  // Load existing gbp-queue.json (generated by /gbp slash command)
  const posts = loadGBPQueue();
  if (!posts.length) {
    console.error("❌  No posts found. Run /gbp slash command first to generate gbp-queue.json.");
    process.exit(1);
  }

  console.log(`  📋  ${posts.length} GBP posts loaded from gbp-queue.json`);
  console.log();

  if (PREVIEW_ONLY) {
    console.log("  👁️  Preview mode — no images or DB insertion.");
    console.log();
    for (const p of posts) {
      console.log(`  ${p.scheduled_display.padEnd(24)} ${p.pillar.padEnd(18)} ${p.cta_type.padEnd(14)} ${p.topic.substring(0, 50)}`);
    }
    console.log();
    return;
  }

  // Generate and upload images
  const enriched = await generateAndUploadAll(posts);

  // Insert into PostgreSQL
  if (!process.env.DATABASE_URL) {
    console.error("❌  DATABASE_URL not set. Cannot insert into queue.");
    process.exit(1);
  }

  await ensureGBPTable();
  await insertGBPPosts(enriched);

  // Summary
  const summary = await getQueueSummary();
  console.log(hr("═"));
  console.log("  ✅  GBP QUEUE READY");
  console.log(hr("─"));
  console.log(`  Queued:   ${summary.queued}`);
  console.log(`  Posted:   ${summary.posted}`);
  console.log(`  Failed:   ${summary.failed}`);
  if (summary.next_date) {
    console.log(`  Next:     ${new Date(summary.next_date).toLocaleDateString("en-GB", { weekday: "short", day: "numeric", month: "short", hour: "2-digit", minute: "2-digit" })}`);
  }
  console.log(hr("═"));
  console.log();
  console.log("  n8n WF7 will post these automatically on schedule.");
  console.log();
}

main().catch((err) => { console.error("\n❌  Fatal:", err); process.exit(1); });
