/**
 * Podcast Episode Generator — Prompt builder and script parser
 *
 * Does NOT call the Claude API. The /podcast slash command (Claude Code)
 * handles all content generation. This module provides:
 *   - buildPodcastPrompt()   → returns the extraction prompt for the slash command
 *   - parsePodcastScript()   → validates and parses the Claude-generated JSON
 *
 * The outro and mid-roll CTAs are hardcoded constants — never regenerated.
 */

import type { PodcastScript, PodcastTip } from "./podcast-types.js";
import { computeLocalPlan, localBriefForPrompt } from "./local-seo.js";

// ── Hardcoded constants — never generated by Claude Code ─────

/** Final sign-off — always used verbatim. */
export const PODCAST_OUTRO =
  "That's your quick tip for today. If you want to see how AI automation can help your business, head to antek automation dot com, or give us a bell on oh three three three, oh three eight, nine nine six oh. Cheers.";

/** Casual blog mention after tip 3 — brief, not pushy. */
export const BLOG_CTA =
  "By the way, there's a full written version of this on the blog if you want the detail. Link's in the show notes.";

/**
 * Generates a URL-safe slug from an episode title.
 */
export function generateSlug(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "")
    .substring(0, 50);
}

/**
 * Returns the extraction prompt for Claude Code to generate a PodcastScript
 * from a blog post. Called once per episode, before TTS generation.
 */
export function buildPodcastPrompt(blogTitle: string, blogContent: string, sourceUrl?: string): string {
  const plan = computeLocalPlan({ title: blogTitle, seed: sourceUrl, extraText: blogContent });
  const localEpisodeRule = plan.location
    ? `This episode has a local angle: "${plan.location}". Allow ONE natural local reference in the spoken script, and you may give episode_title or episode_description a light local framing (e.g. "${plan.location}" once). Do not name the town more than once.`
    : `No local angle for this episode. Keep the script and metadata general — the show already carries the Andover/Hampshire identity at the show level, so most individual episodes should NOT force a town in.`;
  return `You are generating a podcast script for "Quick Tips with Antek Automation" — a 6-7 minute audio episode for UK small business owners. Output a single valid JSON object matching the PodcastScript type. No markdown fences, no extra text — just the JSON.

## Blog post
Title: ${blogTitle}

${blogContent}

${localBriefForPrompt(plan)}

Local episode rule: ${localEpisodeRule}

## Instructions

Extract a 6-7 minute episode from this blog post. Target 850-950 words total (intro + context + all tips + recap — the CTAs and outro are hardcoded and not counted). At natural speech pace (~150 wpm) this gives 6-7 minutes including the hardcoded sections.

The narrator is Andy Norman — founder of Antek Automation, Andover, Hampshire. 30+ years in managed print services before moving into AI automation. Not a tech bro. A practical bloke who gives straight advice.

### Script sections

**intro** — 20-30 seconds (~50-60 words). Start with: "Hey, it's Andy from Antek Automation." Then introduce the topic with a hook — why this matters to the listener right now. "Today I want to talk about [topic] because [concrete reason it matters to service businesses]. Stick around — I've got [number] tips that could [specific benefit]."

**context** — 40-60 seconds (~100-120 words). Two paragraphs. Paint a vivid, specific picture of the problem. Use a real scenario: "Imagine you're a [specific business type] and it's [time of day]. A potential client rings but you're [doing something specific]..." Pull real data or stats from the blog post. Make the listener think "that's me."

**tips** — Array of 5-7 tip objects. Each tip: 2-4 sentences, ~50-80 words. This is the meat of the episode. Number them naturally:
- "Right, tip number one..."
- "Number two, and this is a big one..."
- "Tip three..."
- "Now, number four..."
- "Five, and this is the one most people skip..."
- "Tip six..." (if 6 or 7 tips)
- "And finally, number seven..." (if 7 tips)

Each tip should be deeply practical — not "think about your process" but "open your phone right now, go to settings, and turn on this specific feature." Reference specific tools, prices, timeframes from the blog post. Weave in natural mentions of how this relates to what Antek Automation does — but keep it educational, not salesy.

**recap** — 20-30 seconds (~40-60 words). Must start with: "So to recap:". Summarise the 2-3 most impactful tips. End with a forward-looking line: "Start with [easiest tip] this week and build from there" or similar.

**outro** — Use exactly: "${PODCAST_OUTRO}"

**blog_cta** — Use exactly: "${BLOG_CTA}"

Note: blog_cta is inserted after tip 3 during audio generation. You don't control placement — just include it verbatim. There is no other CTA mid-episode. Keep the tips themselves educational — any Antek mentions should feel like natural context ("this is the kind of thing we help with") not a pitch.

**episode_title** — SEO-friendly title. Clear, specific, includes main keyword. Max 70 characters. Format: "[Topic] — [Number] Tips for [Audience]" or similar.

**episode_description** — 3-5 sentences for podcast apps and RSS.com. This is crucial for SEO/GEO discovery. Must include:
- Main topic keyword in the first sentence
- "Antek Automation" brand mention
- Specific benefit/outcome the listener gets
- The blog post topic as context
- A natural keyword phrase for Apple Podcasts / Spotify search
Example: "Andy Norman from Antek Automation shares five practical ways UK service businesses can stop losing enquiries to missed calls. Based on real data from small businesses, this episode covers AI receptionists, automated follow-ups, and simple phone settings that most owners overlook. If you run a trades, health, or professional services business, these tips could save you three or more lost leads every week."

**seo_keywords** — Array of 5-8 keyword phrases for RSS.com episode keywords. These help with podcast discovery on Apple Podcasts, Spotify, and Google Podcasts. Mix:
- 2-3 specific topic keywords (e.g. "AI receptionist for small business")
- 1-2 industry keywords (e.g. "UK trades business automation")
- 1-2 broader category keywords (e.g. "small business tips")
- 1 brand keyword ("Antek Automation")
All lowercase, natural phrases, not hashtags.

**geo_answer** — ONE self-contained sentence answering the episode's core question. It must stand alone if an AI engine quotes it out of context (no "as I said earlier"). This is the single most citable line for AI search (ChatGPT, Perplexity, Gemini). Natural English, not keyword-stuffed.

**geo_takeaways** — Array of 2-4 short, declarative, standalone statements. Each is a complete fact on its own — the format AI engines lift cleanly into answers.

### Output format

\`\`\`json
{
  "episode_title": "...",
  "episode_description": "3-5 sentences, SEO/GEO rich...",
  "source_blog_url": "...",
  "source_blog_title": "...",
  "intro": "Hey, it's Andy from Antek Automation. Today I want to talk about...",
  "context": "Two paragraphs painting a vivid scenario...",
  "tips": [
    { "tip_number": 1, "text": "Right, tip number one..." },
    { "tip_number": 2, "text": "Number two..." },
    { "tip_number": 3, "text": "Tip three..." },
    { "tip_number": 4, "text": "Now, number four..." },
    { "tip_number": 5, "text": "Five, and this is the one most people skip..." }
  ],
  "blog_cta": "${BLOG_CTA}",
  "recap": "So to recap: ...",
  "outro": "${PODCAST_OUTRO}",
  "seo_keywords": ["ai receptionist for small business", "missed calls uk", "antek automation", "service business tips", "ai automation uk"],
  "geo_answer": "One self-contained sentence answering the episode's core question.",
  "geo_takeaways": ["Standalone fact one.", "Standalone fact two.", "Standalone fact three."]
}
\`\`\`

### Tone rules (non-negotiable)
- British English throughout: colour, organise, whilst, realise, licence, programme, maths, mobile, ring, sort out
- Conversational and direct — sounds like giving advice over a cuppa, not a TED talk
- No corporate speak: never "leverage", "synergy", "game-changing", "revolutionary", "empower"
- Specific and actionable: "Set your voicemail to mention you'll call back within 2 hours" not "improve your communication"
- Numbers spoken as words: "sixty-two percent" not "62%"
- Reference real business types from the article — don't just say "service business"
- Andy's angle: practical, lived experience, straight answer
- Natural Antek Automation mentions: weave the brand into tips naturally ("this is exactly the kind of thing we set up for clients at Antek", "I've seen this work brilliantly for a plumber we work with") — but keep it educational, not a hard sell`;
}

/**
 * Validates and parses the Claude-generated JSON into a PodcastScript.
 * Throws a descriptive error if validation fails.
 * Always overrides outro and CTAs with hardcoded constants.
 * Generates episode_slug from episode_title.
 */
export function parsePodcastScript(output: string): PodcastScript {
  let raw: unknown;
  try {
    raw = JSON.parse(output);
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err);
    throw new Error(`PodcastScript JSON parse error: ${msg}`);
  }

  const obj = raw as Record<string, unknown>;

  const stringFields = [
    "episode_title",
    "episode_description",
    "source_blog_url",
    "source_blog_title",
    "intro",
    "context",
    "recap",
    "outro",
    "blog_cta",
  ] as const;

  for (const field of stringFields) {
    if (typeof obj[field] !== "string") {
      throw new Error(`PodcastScript validation: '${field}' must be a string`);
    }
  }

  if (!Array.isArray(obj.tips)) {
    throw new Error("PodcastScript validation: 'tips' must be an array");
  }
  if (obj.tips.length < 5 || obj.tips.length > 7) {
    throw new Error(
      `PodcastScript validation: 'tips' must have 5-7 items, got ${obj.tips.length}`
    );
  }
  const tips: PodcastTip[] = [];
  for (let i = 0; i < obj.tips.length; i++) {
    const tip = obj.tips[i] as Record<string, unknown>;
    if (typeof tip.text !== "string") {
      throw new Error(`PodcastScript validation: tips[${i}].text must be a string`);
    }
    if (typeof tip.tip_number !== "number") {
      throw new Error(`PodcastScript validation: tips[${i}].tip_number must be a number`);
    }
    tips.push({ tip_number: tip.tip_number, text: tip.text });
  }

  if (!(obj.recap as string).startsWith("So to recap")) {
    throw new Error(
      `PodcastScript validation: 'recap' must start with "So to recap:"`
    );
  }

  // seo_keywords validation
  if (!Array.isArray(obj.seo_keywords)) {
    throw new Error("PodcastScript validation: 'seo_keywords' must be an array");
  }
  if (obj.seo_keywords.length < 5 || obj.seo_keywords.length > 8) {
    throw new Error(
      `PodcastScript validation: 'seo_keywords' must have 5-8 items, got ${obj.seo_keywords.length}`
    );
  }
  for (let i = 0; i < obj.seo_keywords.length; i++) {
    if (typeof obj.seo_keywords[i] !== "string") {
      throw new Error(`PodcastScript validation: seo_keywords[${i}] must be a string`);
    }
  }

  // Word count check (excluding hardcoded outro and blog_cta)
  const scriptWords = [
    obj.intro as string,
    obj.context as string,
    ...tips.map((t) => t.text),
    obj.recap as string,
  ]
    .join(" ")
    .split(/\s+/).length;

  if (scriptWords > 1050) {
    throw new Error(
      `PodcastScript validation: script too long (${scriptWords} words, target max 950)`
    );
  }

  // GEO fields are optional — validate only if present
  if (obj.geo_answer !== undefined && typeof obj.geo_answer !== "string") {
    throw new Error("PodcastScript validation: 'geo_answer' must be a string when present");
  }
  if (obj.geo_takeaways !== undefined && !Array.isArray(obj.geo_takeaways)) {
    throw new Error("PodcastScript validation: 'geo_takeaways' must be an array when present");
  }

  return {
    episode_title: obj.episode_title as string,
    episode_description: obj.episode_description as string,
    episode_slug: generateSlug(obj.episode_title as string),
    source_blog_url: obj.source_blog_url as string,
    source_blog_title: obj.source_blog_title as string,
    intro: obj.intro as string,
    context: obj.context as string,
    tips,
    blog_cta: BLOG_CTA,   // always enforced
    recap: obj.recap as string,
    outro: PODCAST_OUTRO,  // always enforced
    seo_keywords: obj.seo_keywords as string[],
    geo_answer: obj.geo_answer as string | undefined,
    geo_takeaways: obj.geo_takeaways as string[] | undefined,
  };
}

/**
 * Assembles a clean, readable transcript from the episode script in spoken
 * order. Transcript text is the primary thing AI engines index from audio, so
 * it goes into the RSS.com show notes below the GEO block.
 */
export function buildEpisodeTranscript(script: PodcastScript): string {
  const parts: string[] = [
    script.intro,
    script.context,
    ...script.tips.map((t) => t.text),
    script.blog_cta,
    script.recap,
    script.outro,
  ];
  return parts
    .map((p) => (p ?? "").trim())
    .filter(Boolean)
    .join("\n\n");
}
