/**
 * YouTube Shorts Generator — Prompt builder and script parser
 *
 * Does NOT call the Claude API. The /shorts slash command (Claude Code)
 * handles all content generation. This module provides:
 *   - buildPrompt()     → returns the extraction prompt for the slash command
 *   - parseShortScript() → validates and parses the Claude-generated JSON
 */

import type { ShortScript, ShortSlide, ShortsPlatform, PlatformMeta } from "./shorts-types.js";

// Hardcoded CTA voiceover — never generated by Claude Code
// CTA voiceover is split in shorts-voice.ts: part 1 (website) + 5s silence + part 2 (phone).
// The voiceover_text field here reflects the full intended script for reference only.
const CTA_VOICEOVER_TEXT =
  "Follow Antek Automation for more tips like this. Visit antek automation dot com. [5s pause] Or call oh three three three, oh three eight, nine nine six oh.";

/**
 * Returns the extraction prompt for Claude Code to reason over a blog post
 * and produce a valid ShortScript JSON object.
 */
export function buildPrompt(title: string, content: string): string {
  return `You are generating a YouTube Shorts script from a blog post. Output a single valid JSON object matching the ShortScript type. No markdown fences, no extra text — just the JSON.

## Blog post
Title: ${title}

${content}

## Instructions

Extract a 6-slide script for a 30-second YouTube Short. Be concise and punchy — this is a scroll-stopping short-form video, not a summary.

### Slides (in order)

1. **hook** — The single most surprising stat, counterintuitive claim, or bold question from the post. Max 15 words. Must stop the scroll. Use a question or a shocking number.

2. **tip** (tipNumber: 1) — First actionable tip. Max 12 words. Start with a verb. Specific, not vague.

3. **tip** (tipNumber: 2) — Second actionable tip. Max 12 words. Different angle from tip 1.

4. **tip** (tipNumber: 3) — Third actionable tip. Max 12 words. The most memorable of the three.

5. **summary** — One-line takeaway that wraps up the value. Max 15 words. Should make the viewer feel they learned something.

6. **cta** — Leave text as empty string "". Set voiceover_text to exactly: "${CTA_VOICEOVER_TEXT}"

### Voiceover text (voiceover_text field)

Each slide needs a natural spoken version of its content — this is read aloud by a TTS voice, not shown on screen.

Rules:
- British English (colour, organise, whilst)
- Conversational and direct — sounds like a confident business owner talking, not a script
- Numbers as words: "sixty-two percent" not "62%"
- Slightly longer than on-screen text but still concise (max 20 words per slide)
- No jargon, no filler words
- Hook: open with "Did you know..." or turn the stat into a punchy question
- Tips: "Tip one: [slightly expanded version]" — more conversational than the on-screen text
- Summary: "So remember: [conversational recap]"
- CTA: use the exact hardcoded text — do NOT paraphrase

### YouTube metadata

- **youtubeTitle**: Max 60 characters. Hook-first. Include the main topic keyword. No clickbait.
- **youtubeDescription**: Max 200 characters. Expand on the title. Include 1-2 keywords naturally. End with "Full guide: [blog URL]"
- **youtubeTags**: Exactly 5 hashtags. Must include #Shorts. Mix broad and specific tags.

### Output format

\`\`\`
{
  "slides": [
    { "type": "hook", "text": "...", "voiceover_text": "Did you know..." },
    { "type": "tip", "text": "...", "tipNumber": 1, "voiceover_text": "Tip one: ..." },
    { "type": "tip", "text": "...", "tipNumber": 2, "voiceover_text": "Tip two: ..." },
    { "type": "tip", "text": "...", "tipNumber": 3, "voiceover_text": "Tip three: ..." },
    { "type": "summary", "text": "...", "voiceover_text": "So remember: ..." },
    { "type": "cta", "text": "", "voiceover_text": "${CTA_VOICEOVER_TEXT}" }
  ],
  "sourceBlogUrl": "...",
  "sourceBlogTitle": "...",
  "youtubeTitle": "...",
  "youtubeDescription": "...",
  "youtubeTags": ["#Shorts", "...", "...", "...", "..."]
}
\`\`\`

Andy's voice rules (apply throughout):
- UK English (colour, organise, whilst)
- Direct and practical — no hype words
- Specific numbers and data from the actual post
- Never: "game-changing", "revolutionary", "leverage", "empower"`;
}

/**
 * Validates and parses the Claude-generated JSON into a ShortScript object.
 * Throws a descriptive error if validation fails.
 * Always overrides the CTA slide's voiceover_text with the hardcoded constant.
 */
export function parseShortScript(jsonStr: string): ShortScript {
  let raw: unknown;
  try {
    raw = JSON.parse(jsonStr);
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err);
    throw new Error(`ShortScript JSON parse error: ${msg}`);
  }

  const obj = raw as Record<string, unknown>;

  if (!Array.isArray(obj.slides)) {
    throw new Error("ShortScript validation: 'slides' must be an array");
  }
  if (obj.slides.length !== 6) {
    throw new Error(`ShortScript validation: expected 6 slides, got ${obj.slides.length}`);
  }

  const expectedTypes = ["hook", "tip", "tip", "tip", "summary", "cta"];
  for (let i = 0; i < obj.slides.length; i++) {
    const slide = obj.slides[i] as Record<string, unknown>;
    if (typeof slide.text !== "string") {
      throw new Error(`ShortScript validation: slide[${i}].text must be a string`);
    }
    if (slide.type !== expectedTypes[i]) {
      throw new Error(
        `ShortScript validation: slide[${i}].type expected "${expectedTypes[i]}", got "${slide.type}"`
      );
    }
    if (slide.type === "tip" && typeof slide.tipNumber !== "number") {
      throw new Error(`ShortScript validation: slide[${i}] is type "tip" but tipNumber is missing`);
    }
    if (typeof slide.voiceover_text !== "string") {
      throw new Error(`ShortScript validation: slide[${i}].voiceover_text must be a string`);
    }
  }

  if (typeof obj.youtubeTitle !== "string") {
    throw new Error("ShortScript validation: 'youtubeTitle' must be a string");
  }
  if (obj.youtubeTitle.length > 60) {
    throw new Error(
      `ShortScript validation: youtubeTitle too long (${obj.youtubeTitle.length} chars, max 60)`
    );
  }

  if (typeof obj.youtubeDescription !== "string") {
    throw new Error("ShortScript validation: 'youtubeDescription' must be a string");
  }
  if (obj.youtubeDescription.length > 200) {
    throw new Error(
      `ShortScript validation: youtubeDescription too long (${obj.youtubeDescription.length} chars, max 200)`
    );
  }

  if (!Array.isArray(obj.youtubeTags) || obj.youtubeTags.length !== 5) {
    throw new Error("ShortScript validation: 'youtubeTags' must be an array of exactly 5 items");
  }
  if (!obj.youtubeTags.includes("#Shorts")) {
    throw new Error("ShortScript validation: 'youtubeTags' must include #Shorts");
  }

  if (typeof obj.sourceBlogUrl !== "string" || typeof obj.sourceBlogTitle !== "string") {
    throw new Error("ShortScript validation: 'sourceBlogUrl' and 'sourceBlogTitle' are required");
  }

  // Always enforce the hardcoded CTA voiceover regardless of what was generated
  const slides = obj.slides as ShortSlide[];
  slides[5].voiceover_text = CTA_VOICEOVER_TEXT;

  return {
    slides,
    sourceBlogUrl: obj.sourceBlogUrl as string,
    sourceBlogTitle: obj.sourceBlogTitle as string,
    youtubeTitle: obj.youtubeTitle as string,
    youtubeDescription: obj.youtubeDescription as string,
    youtubeTags: obj.youtubeTags as string[],
  };
}

/**
 * Generates platform-specific metadata for a Short from the validated script.
 * Called once per target platform after parseShortScript() validates the script.
 * Derives captions and metadata from the slide content — no external API calls.
 *
 * YouTube:  title + full description (blog URL first) + hashtags
 * Instagram: caption (hook → tips → CTA) + 17 hashtags in a separate block
 * Facebook:  conversational caption with question ending + 4 hashtags inline
 */
export function generatePlatformMeta(script: ShortScript, platform: ShortsPlatform): PlatformMeta {
  const hookSlide = script.slides.find((s) => s.type === "hook");
  const tipSlides = script.slides.filter((s) => s.type === "tip");
  const summarySlide = script.slides.find((s) => s.type === "summary");

  const hookText = hookSlide?.text ?? script.sourceBlogTitle;
  const summaryText = summarySlide?.text ?? "";
  const tip1 = tipSlides[0]?.text ?? "";
  const tip2 = tipSlides[1]?.text ?? "";
  const tip3 = tipSlides[2]?.text ?? "";

  if (platform === "youtube") {
    return {
      platform: "youtube",
      title: script.youtubeTitle,
      description: `${script.sourceBlogUrl}\n\n${script.youtubeDescription}`,
      hashtags: script.youtubeTags,
      caption: "",
    };
  }

  if (platform === "instagram") {
    const hashtags = [
      "#AntekAutomation",
      "#AIAutomation",
      "#UKSmallBusiness",
      "#BusinessAutomation",
      "#AIReceptionist",
      "#VoiceAI",
      "#SmallBusiness",
      "#ServiceBusiness",
      "#WorkflowAutomation",
      "#AIForBusiness",
      "#UKBusiness",
      "#BusinessOwner",
      "#AutomationTools",
      "#n8n",
      "#RetellAI",
      "#AITools",
      "#Shorts",
    ];
    const tipLines = [tip1, tip2, tip3].filter(Boolean).map((t) => `→ ${t}`);
    const bodyLines: string[] = [
      hookText,
      "",
      ...tipLines,
      ...(summaryText ? ["", summaryText] : []),
      "",
      "Follow @AntekAutomation for AI automation tips built for UK small businesses.",
      "More at antekautomation.com",
    ];
    const caption = bodyLines.join("\n") + "\n\n" + hashtags.join(" ");
    return {
      platform: "instagram",
      title: "",
      description: "",
      hashtags,
      caption,
    };
  }

  // facebook — conversational, question-based, 3–5 hashtags only
  const hashtags = ["#AIAutomation", "#SmallBusiness", "#UKBusiness", "#BusinessTips"];
  const intro = hookText.endsWith("?") ? hookText : `${hookText} — sound familiar?`;
  const fbTipLines = [tip1, tip2].filter(Boolean).map((t) => `${t}.`);
  const captionLines: string[] = [
    intro,
    "",
    ...fbTipLines,
    ...(summaryText ? [summaryText] : []),
    "",
    "See how we fix this for UK service businesses at antekautomation.com or follow @AntekAutomation.",
    "",
    "What's the biggest admin headache in your business right now?",
    "",
    hashtags.join(" "),
  ];
  return {
    platform: "facebook",
    title: "",
    description: "",
    hashtags,
    caption: captionLines.join("\n"),
  };
}
