/**
 * YouTube Shorts Generator — Prompt builder and script parser
 *
 * Does NOT call the Claude API. The /shorts slash command (Claude Code)
 * handles all content generation. This module provides:
 *   - buildPrompt()     → returns the extraction prompt for the slash command
 *   - parseShortScript() → validates and parses the Claude-generated JSON
 */

import type { ShortScript, ShortSlide, ShortsPlatform, PlatformMeta } from "./shorts-types.js";
import {
  computeLocalPlan,
  localBriefForPrompt,
  localYoutubeTitleSuffix,
  localDescriptionOpener,
  localCaptionMention,
  localHashtags,
  buildGeoBlock,
  type LocalPlan,
} from "./local-seo.js";

// Hardcoded CTA voiceover — never generated by Claude Code
// CTA voiceover is split in shorts-voice.ts: part 1 (website) + 5s silence + part 2 (phone).
// The voiceover_text field here reflects the full intended script for reference only.
const CTA_VOICEOVER_TEXT =
  "Follow Antek Automation for more tips like this. Visit antek automation dot com. [5s pause] Or call oh three three three, oh three eight, nine nine six oh.";

/**
 * Returns the extraction prompt for Claude Code to reason over a blog post
 * and produce a valid ShortScript JSON object.
 */
export function buildPrompt(title: string, content: string, sourceUrl?: string): string {
  const plan = computeLocalPlan({ title, seed: sourceUrl, extraText: content });
  return `You are generating a YouTube Shorts script from a blog post. Output a single valid JSON object matching the ShortScript type. No markdown fences, no extra text — just the JSON.

## Blog post
Title: ${title}

${content}

${localBriefForPrompt(plan)}

## Instructions

Extract a 6-slide script for a 30-second YouTube Short. Be concise and punchy — this is a scroll-stopping short-form video, not a summary.

### Slides (in order)

1. **hook** — The single most surprising stat, counterintuitive claim, or bold question from the post. Max 15 words. Must stop the scroll. Use a question or a shocking number.

2. **tip** (tipNumber: 1) — First actionable tip. Max 12 words. Start with a verb. Specific, not vague.

3. **tip** (tipNumber: 2) — Second actionable tip. Max 12 words. Different angle from tip 1.

4. **tip** (tipNumber: 3) — Third actionable tip. Max 12 words. The most memorable of the three.

5. **summary** — One-line takeaway that wraps up the value. Max 15 words. Should make the viewer feel they learned something.

6. **cta** — Leave text as empty string "". Set voiceover_text to exactly: "${CTA_VOICEOVER_TEXT}"

### Voiceover text (voiceover_text field)

Each slide needs a natural spoken version of its content — this is read aloud by a TTS voice, not shown on screen.

Rules:
- British English (colour, organise, whilst)
- Conversational and direct — sounds like a confident business owner talking, not a script
- Numbers as words: "sixty-two percent" not "62%"
- Slightly longer than on-screen text but still concise (max 20 words per slide)
- No jargon, no filler words
- Hook: open with "Did you know..." or turn the stat into a punchy question
- Tips: "Tip one: [slightly expanded version]" — more conversational than the on-screen text
- Summary: "So remember: [conversational recap]"
- CTA: use the exact hardcoded text — do NOT paraphrase

### YouTube metadata

- **youtubeTitle**: Max 60 characters. Hook-first. Include the main topic keyword. No clickbait. Do NOT add any town or county name — local framing is applied downstream.
- **youtubeDescription**: Max 200 characters. Expand on the title. Include 1-2 keywords naturally. End with "Full guide: [blog URL]". Do NOT add place names here either.
- **youtubeTags**: Exactly 5 hashtags. Must include #Shorts. Mix broad and specific tags. No local hashtags — those are added downstream when relevant.

### GEO / AI-search fields (for the YouTube description)

These make the description citable by AI engines (ChatGPT, Perplexity, Gemini). Write them as natural, genuinely useful English — not keyword-stuffed.

- **geo_answer**: ONE self-contained sentence answering the post's core question. It must stand alone if quoted out of context — no "as mentioned above". This is the single most citable line.
- **geo_takeaways**: 2-4 short, declarative, standalone statements. Each is a complete fact on its own — the format AI engines lift cleanly.

### Output format

\`\`\`
{
  "slides": [
    { "type": "hook", "text": "...", "voiceover_text": "Did you know..." },
    { "type": "tip", "text": "...", "tipNumber": 1, "voiceover_text": "Tip one: ..." },
    { "type": "tip", "text": "...", "tipNumber": 2, "voiceover_text": "Tip two: ..." },
    { "type": "tip", "text": "...", "tipNumber": 3, "voiceover_text": "Tip three: ..." },
    { "type": "summary", "text": "...", "voiceover_text": "So remember: ..." },
    { "type": "cta", "text": "", "voiceover_text": "${CTA_VOICEOVER_TEXT}" }
  ],
  "sourceBlogUrl": "...",
  "sourceBlogTitle": "...",
  "youtubeTitle": "...",
  "youtubeDescription": "...",
  "youtubeTags": ["#Shorts", "...", "...", "...", "..."],
  "geo_answer": "One self-contained sentence answering the core question.",
  "geo_takeaways": ["Standalone fact one.", "Standalone fact two.", "Standalone fact three."]
}
\`\`\`

Andy's voice rules (apply throughout):
- UK English (colour, organise, whilst)
- Direct and practical — no hype words
- Specific numbers and data from the actual post
- Never: "game-changing", "revolutionary", "leverage", "empower"`;
}

/**
 * Validates and parses the Claude-generated JSON into a ShortScript object.
 * Throws a descriptive error if validation fails.
 * Always overrides the CTA slide's voiceover_text with the hardcoded constant.
 */
export function parseShortScript(jsonStr: string): ShortScript {
  let raw: unknown;
  try {
    raw = JSON.parse(jsonStr);
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err);
    throw new Error(`ShortScript JSON parse error: ${msg}`);
  }

  const obj = raw as Record<string, unknown>;

  if (!Array.isArray(obj.slides)) {
    throw new Error("ShortScript validation: 'slides' must be an array");
  }
  if (obj.slides.length !== 6) {
    throw new Error(`ShortScript validation: expected 6 slides, got ${obj.slides.length}`);
  }

  const expectedTypes = ["hook", "tip", "tip", "tip", "summary", "cta"];
  for (let i = 0; i < obj.slides.length; i++) {
    const slide = obj.slides[i] as Record<string, unknown>;
    if (typeof slide.text !== "string") {
      throw new Error(`ShortScript validation: slide[${i}].text must be a string`);
    }
    if (slide.type !== expectedTypes[i]) {
      throw new Error(
        `ShortScript validation: slide[${i}].type expected "${expectedTypes[i]}", got "${slide.type}"`
      );
    }
    if (slide.type === "tip" && typeof slide.tipNumber !== "number") {
      throw new Error(`ShortScript validation: slide[${i}] is type "tip" but tipNumber is missing`);
    }
    if (typeof slide.voiceover_text !== "string") {
      throw new Error(`ShortScript validation: slide[${i}].voiceover_text must be a string`);
    }
  }

  if (typeof obj.youtubeTitle !== "string") {
    throw new Error("ShortScript validation: 'youtubeTitle' must be a string");
  }
  if (obj.youtubeTitle.length > 60) {
    throw new Error(
      `ShortScript validation: youtubeTitle too long (${obj.youtubeTitle.length} chars, max 60)`
    );
  }

  if (typeof obj.youtubeDescription !== "string") {
    throw new Error("ShortScript validation: 'youtubeDescription' must be a string");
  }
  if (obj.youtubeDescription.length > 200) {
    throw new Error(
      `ShortScript validation: youtubeDescription too long (${obj.youtubeDescription.length} chars, max 200)`
    );
  }

  if (!Array.isArray(obj.youtubeTags) || obj.youtubeTags.length !== 5) {
    throw new Error("ShortScript validation: 'youtubeTags' must be an array of exactly 5 items");
  }
  if (!obj.youtubeTags.includes("#Shorts")) {
    throw new Error("ShortScript validation: 'youtubeTags' must include #Shorts");
  }

  if (typeof obj.sourceBlogUrl !== "string" || typeof obj.sourceBlogTitle !== "string") {
    throw new Error("ShortScript validation: 'sourceBlogUrl' and 'sourceBlogTitle' are required");
  }

  // GEO fields are optional — validate only if present
  if (obj.geo_answer !== undefined && typeof obj.geo_answer !== "string") {
    throw new Error("ShortScript validation: 'geo_answer' must be a string when present");
  }
  if (obj.geo_takeaways !== undefined && !Array.isArray(obj.geo_takeaways)) {
    throw new Error("ShortScript validation: 'geo_takeaways' must be an array when present");
  }

  // Always enforce the hardcoded CTA voiceover regardless of what was generated
  const slides = obj.slides as ShortSlide[];
  slides[5].voiceover_text = CTA_VOICEOVER_TEXT;

  return {
    slides,
    sourceBlogUrl: obj.sourceBlogUrl as string,
    sourceBlogTitle: obj.sourceBlogTitle as string,
    youtubeTitle: obj.youtubeTitle as string,
    youtubeDescription: obj.youtubeDescription as string,
    youtubeTags: obj.youtubeTags as string[],
    geo_answer: obj.geo_answer as string | undefined,
    geo_takeaways: obj.geo_takeaways as string[] | undefined,
  };
}

/** Merge local hashtags into a capped set, preserving `keep` tags (e.g. #Shorts). */
function mergeHashtags(base: string[], local: string[], cap: number, keep: string[] = []): string[] {
  const pinned = base.filter((t) => keep.includes(t));
  const rest = base.filter((t) => !keep.includes(t));
  const merged = [...pinned, ...local];
  for (const t of rest) {
    if (merged.length >= cap) break;
    if (!merged.includes(t)) merged.push(t);
  }
  return merged.slice(0, cap);
}

export interface PlatformMetaOptions {
  /** Pre-computed local plan (shared across an asset's platforms). */
  plan?: LocalPlan;
  /** Anti-duplication salt — re-rolls the seed-driven local choices. */
  salt?: number;
}

/**
 * Generates platform-specific metadata for a Short from the validated script.
 * Called once per target platform after parseShortScript() validates the script.
 * Derives captions and metadata from the slide content — no external API calls.
 *
 * Audience + local angle come from the shared local-seo module:
 *   - copy is written for the chosen vertical's reader (not generic "service businesses")
 *   - when a local anchor is present, the town is woven into titles/descriptions/
 *     captions and a small rotating local hashtag set is added
 *   - when no anchor is present, copy stays clean with no place names or local tags
 *
 * Pass `opts.plan` to share one plan across all of an asset's platforms; pass
 * `opts.salt` to re-roll local choices when the batch dedup detects a collision.
 */
export function generatePlatformMeta(
  script: ShortScript,
  platform: ShortsPlatform,
  opts: PlatformMetaOptions = {}
): PlatformMeta {
  const plan =
    opts.plan ??
    computeLocalPlan({ title: script.sourceBlogTitle, seed: script.sourceBlogUrl, salt: opts.salt });
  const loc = plan.location;
  const seed = plan.seed;
  const reader = plan.vertical.reader;

  const hookSlide = script.slides.find((s) => s.type === "hook");
  const tipSlides = script.slides.filter((s) => s.type === "tip");
  const summarySlide = script.slides.find((s) => s.type === "summary");

  const hookText = hookSlide?.text ?? script.sourceBlogTitle;
  const summaryText = summarySlide?.text ?? "";
  const tip1 = tipSlides[0]?.text ?? "";
  const tip2 = tipSlides[1]?.text ?? "";
  const tip3 = tipSlides[2]?.text ?? "";

  if (platform === "youtube") {
    // Keyword-first title; weave the location only if it still fits in 60 chars.
    let title = script.youtubeTitle;
    if (loc) {
      const suffix = localYoutubeTitleSuffix(loc, seed);
      if (title.length + suffix.length <= 60) title = `${title}${suffix}`;
    }
    const descBody = loc
      ? `${localDescriptionOpener(loc, seed)}\n${script.youtubeDescription}`
      : script.youtubeDescription;
    const hashtags = loc
      ? mergeHashtags(script.youtubeTags, localHashtags(loc, seed, 1), 5, ["#Shorts"])
      : script.youtubeTags;
    // GEO / AI-search block — YouTube description only (not IG/FB captions)
    const geoBlock = buildGeoBlock({
      post: { answer: script.geo_answer ?? "", takeaways: script.geo_takeaways ?? [], seed },
      vertical: plan.vertical,
      localAngle: loc,
      format: "text",
    });
    const description = geoBlock
      ? `${script.sourceBlogUrl}\n\n${descBody}\n\n${geoBlock}`
      : `${script.sourceBlogUrl}\n\n${descBody}`;
    return {
      platform: "youtube",
      title,
      description,
      hashtags,
      caption: "",
    };
  }

  if (platform === "instagram") {
    // Instagram caps at 5 hashtags per Blotato — local tags must fit inside the 5.
    const baseTags = ["#SmallBusinessTips", "#ServiceBusiness", "#BusinessOwner", "#Reels"];
    const hashtags = loc
      ? mergeHashtags(baseTags, localHashtags(loc, seed, 2), 5)
      : [...baseTags, "#LocalBusiness"];
    const tipLines = [tip1, tip2, tip3].filter(Boolean).map((t) => `→ ${t}`);
    const bodyLines: string[] = [
      hookText,
      "",
      ...tipLines,
      ...(summaryText ? ["", summaryText] : []),
      ...(loc ? ["", localCaptionMention(loc, seed)] : []),
      "",
      `Follow @AntekAutomation for practical tips built for ${reader}.`,
      "More at antekautomation.com",
    ];
    const caption = bodyLines.join("\n") + "\n\n" + hashtags.join(" ");
    return {
      platform: "instagram",
      title: "",
      description: "",
      hashtags,
      caption,
    };
  }

  if (platform === "linkedin") {
    const baseTags = ["#SmallBusiness", "#ServiceBusiness", "#BusinessOwner", "#Productivity"];
    const hashtags = loc ? mergeHashtags(baseTags, localHashtags(loc, seed, 1), 5) : baseTags;
    const tipLines = [tip1, tip2, tip3].filter(Boolean).map((t, i) => `${i + 1}. ${t}.`);
    const liLines: string[] = [
      hookText,
      "",
      ...tipLines,
      ...(summaryText ? ["", summaryText] : []),
      ...(loc ? ["", localCaptionMention(loc, seed)] : []),
      "",
      `More practical guides for ${reader} at antekautomation.com.`,
      "",
      hashtags.join(" "),
    ];
    return {
      platform: "linkedin",
      title: "",
      description: "",
      hashtags,
      caption: liLines.join("\n"),
    };
  }

  if (platform === "twitter") {
    // X / Twitter: 280 char cap. Hook line only, no hashtags noise, link to blog
    let body = hookText;
    if (body.length > 240) body = body.slice(0, 237) + "...";
    const caption = `${body}\n\n${script.sourceBlogUrl}`;
    return {
      platform: "twitter",
      title: "",
      description: "",
      hashtags: [],
      caption,
    };
  }

  // facebook — conversational, question ending, 4-5 hashtags inline
  const baseTags = ["#SmallBusiness", "#ServiceBusiness", "#UKBusiness", "#BusinessTips"];
  const hashtags = loc ? mergeHashtags(baseTags, localHashtags(loc, seed, 1), 5) : baseTags;
  const intro = hookText.endsWith("?") ? hookText : `${hookText} — sound familiar?`;
  const fbTipLines = [tip1, tip2].filter(Boolean).map((t) => `${t}.`);
  const captionLines: string[] = [
    intro,
    "",
    ...fbTipLines,
    ...(summaryText ? [summaryText] : []),
    ...(loc ? ["", localCaptionMention(loc, seed)] : []),
    "",
    `We help ${reader} catch what they're missing. antekautomation.com`,
    "",
    "What's costing your firm the most time right now?",
    "",
    hashtags.join(" "),
  ];
  return {
    platform: "facebook",
    title: "",
    description: "",
    hashtags,
    caption: captionLines.join("\n"),
  };
}
