/**
 * Content loader + scheduling.
 *
 * Content is generated by Claude Code in the conversation and saved to content.json.
 * This module reads that file and applies scheduling times.
 *
 * Two entry points:
 *   generateIdeas()          — reads content.json (pillar-based)
 *   generateIdeasFromBriefs() — reads content.json (brief-seeded), or generates
 *                               scheduling from seeds if content.json has the data
 *
 * Scheduling times are assigned here (tomorrow onwards, 08:00 + 12:00 UK time).
 */

import { readFileSync, existsSync } from "fs";
import { join } from "path";
import type { ArticleBrief } from "./load-briefs.js";
import type { ContentIdea, Pillar, Platform, ContentCategory } from "./types.js";

const CONTENT_FILE = join(process.cwd(), "content.json");

const PILLAR_ROTATION: Pillar[] = ["ai_automation", "voice_ai", "growth_digital"];
const CATEGORY_ROTATION: ContentCategory[] = [
  "how_to",
  "tip",
  "thought_leadership",
  "case_study",
  "news",
  "comparison",
  "tutorial",
  "quick_win",
  "product_feature",
  "industry_news",
  "video_content",
];

// ── Scheduling ─────────────────────────────────────────────────

interface ScheduleSlot {
  iso: string;
  display: string;
}

// 1 post/day at 08:00 over 14 days
function buildSchedule(count: number, startDate?: string): ScheduleSlot[] {
  const slots: ScheduleSlot[] = [];
  const tomorrow = startDate ? new Date(startDate + "T00:00:00") : new Date();
  if (!startDate) tomorrow.setDate(tomorrow.getDate() + 1);
  tomorrow.setHours(0, 0, 0, 0);

  for (let i = 0; i < count; i++) {
    const dayOffset = i;
    const hour = 8;

    const date = new Date(tomorrow);
    date.setDate(date.getDate() + dayOffset);
    date.setHours(hour, 0, 0, 0);

    const display = date.toLocaleDateString("en-GB", {
      weekday: "short",
      day: "numeric",
      month: "short",
      timeZone: "Europe/London",
    }) + ` at ${hour}:00`;

    slots.push({ iso: date.toISOString(), display });
  }
  return slots;
}

// ── Load content.json ──────────────────────────────────────────

function loadContentFile(): unknown[] {
  if (!existsSync(CONTENT_FILE)) {
    console.error(`\n❌  content.json not found.`);
    console.error(`    Ask Claude Code to generate content first:`);
    console.error(`    "Generate 14 content ideas for this week"\n`);
    process.exit(1);
  }

  const raw = JSON.parse(readFileSync(CONTENT_FILE, "utf-8"));
  if (!Array.isArray(raw)) throw new Error("content.json must be a JSON array");
  return raw;
}

// ── Assemble ContentIdea[] ─────────────────────────────────────

function assembleIdeas(
  raw: unknown[],
  schedule: ScheduleSlot[],
  idPrefix: string,
): ContentIdea[] {
  return raw.map((item: any, i) => {
    const slot = schedule[i] || schedule[schedule.length - 1];

    const platforms: Platform[] = ["linkedin", "twitter", "facebook", "instagram"];

    // Inject scheduling times
    for (const p of platforms) {
      if (item.variants?.[p]) {
        item.variants[p].scheduled_at = slot.iso;
        item.variants[p].scheduled_display = slot.display;
      }
    }

    return {
      idea_id: item.idea_id || `${idPrefix}_${i}`,
      pillar: item.pillar,
      content_category: item.content_category,
      topic: item.topic,
      hook: item.hook || "",
      variants: item.variants,
      image_prompt_landscape: item.image_prompt_landscape || "",
      image_prompt_square: item.image_prompt_square || "",
      video_motion_prompt: item.video_motion_prompt || "",
    } as ContentIdea;
  });
}

// ── Public: pillar-based generation ────────────────────────────

export async function generateIdeas(
  count: number,
  forcePillar?: Pillar,
  forceCategory?: ContentCategory,
  startDate?: string,
): Promise<ContentIdea[]> {
  console.log(`  📂  Reading content.json...`);
  const raw = loadContentFile();

  // Take only what we need
  const items = raw.slice(0, count);
  const schedule = buildSchedule(items.length, startDate);

  return assembleIdeas(items, schedule, "idea");
}

// ── Public: brief-seeded generation ────────────────────────────

export async function generateIdeasFromBriefs(
  seeds: Array<{ brief: ArticleBrief; pillar: Pillar; content_category: ContentCategory }>,
): Promise<ContentIdea[]> {
  console.log(`  📂  Reading content.json...`);
  const raw = loadContentFile();

  const count = Math.min(raw.length, seeds.length);
  const items = raw.slice(0, count);
  const schedule = buildSchedule(count);

  // Inject brief IDs into idea IDs
  const ideas = assembleIdeas(items, schedule, "brief").map((idea, j) => ({
    ...idea,
    idea_id: seeds[j] ? `brief_${seeds[j].brief.id}_${j}` : idea.idea_id,
  }));

  return ideas;
}
