/**
 * Podcast Episode Pipeline — Type definitions
 */

export type PodcastStatus = "queued" | "uploaded" | "distributed" | "failed";

/**
 * A single tip in the podcast script.
 * tip_number is 1-indexed; text is the full spoken tip.
 */
export interface PodcastTip {
  tip_number: number;
  text: string;
}

/**
 * The structured script for a single podcast episode.
 * Generated by Claude Code from a blog post, validated by parsePodcastScript().
 *
 * Episode structure (~6 minutes):
 *   intro → context → tips (5-7) with blog mention → recap → outro
 *
 * The outro is always the hardcoded PODCAST_OUTRO constant — never generated.
 * The blog_cta is a hardcoded constant inserted after tip 3 — never generated.
 */
export interface PodcastScript {
  episode_title: string;       // SEO-friendly episode title (max 70 chars)
  episode_description: string; // SEO-rich podcast app description (3-5 sentences, keyword-packed)
  episode_slug: string;        // URL-safe slug derived from title
  source_blog_url: string;
  source_blog_title: string;
  intro: string;               // ~20-30 seconds — "Hey, it's Andy from Antek Automation..."
  context: string;             // ~40-60 seconds — problem/opportunity deep dive
  tips: PodcastTip[];          // 5-7 tips, each 2-4 sentences
  blog_cta: string;            // Casual blog mention after tip 3 (hardcoded constant)
  recap: string;               // ~20-30 seconds — "So to recap: ..."
  outro: string;               // Always the hardcoded PODCAST_OUTRO constant
  // SEO/GEO metadata for RSS.com
  seo_keywords: string[];      // 5-8 keywords for RSS.com episode keywords + Apple Podcasts discovery
}

export interface PodcastEpisode {
  audio_path: string;
  r2_url?: string;
  rsscom_episode_id?: string;
  duration_seconds: number;
  script: PodcastScript;
  status: PodcastStatus;
}

/**
 * Response from RSS.com after creating an episode via their API.
 *
 * RSS.com API v4:
 *   POST /v4/podcasts/{podcast_id}/episodes → 201 Episode
 *   Episode.status: "draft" | "scheduled" | "published"
 */
export interface RSSComEpisodeResult {
  episode_id: number;        // RSS.com integer episode ID
  status: string;            // "draft" | "scheduled" | "published"
  audio_url: string | null;  // Public CDN URL once transcoding completes
  audio_upload_id: string;   // The presigned upload ID used to create this episode
  cover_upload_id?: string;  // The presigned upload ID for episode cover art
  dashboard_url?: string;    // RSS.com dashboard link
  website_url?: string;      // RSS.com public episode page
}

export interface PodcastDbRecord {
  id: string;
  episode_title: string;
  episode_description?: string;
  episode_slug: string;
  episode_number?: number;
  audio_path: string;
  r2_url?: string;
  rsscom_episode_id?: string;
  rsscom_audio_id?: string;
  youtube_video_path?: string;
  youtube_r2_url?: string;
  blog_source_url?: string;
  ghost_post_id?: string;
  duration_seconds?: number;
  file_size_bytes?: number;
  ghost_embedded: boolean;
  rsscom_published: boolean;
  youtube_queued: boolean;
  status: PodcastStatus;
  created_at: Date;
  published_at?: Date;
}
